# Generated by Django 4.2.3 on 2023-08-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usergroupassociation_userpermissionassociation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
